#ifndef UNIVERSITY_TIME_UTILS_H
#define UNIVERSITY_TIME_UTILS_H

#define SECONDS_IN_MINUTE 60
#define MINUTES_IN_HOUR 60
#define HOURS_IN_DAY 24
#define DAYS_IN_MOUNT 30
#define MOUNTS_IN_QUARTER 3

#define DAYS_IN_YEAR 365
#define MOUNTS_IN_YEAR 12
#define QUARTERS_IN_YEAR 4

#define SECONDS_IN_DAY (SECONDS_IN_MINUTE * MINUTES_IN_HOUR * HOURS_IN_DAY)

#endif //UNIVERSITY_TIME_UTILS_H
